config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'search', to: "boyfriends#search", as: "search"
  delete 'boyfriends/:id', to: 'boyfriends#destroy', as: 'delete_boyfriend'
  # patch 'boyfriends/:id', to: 'boyfriends#update', as: 'update_boyfriend'

  get 'reservations/dashboard', to: "reservations#dashboard"
  get "confirmation", to:'boyfriends#confirmation', as: 'confirmation'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boyfriends, only: %i[show create new edit update destroy] do
    collection do
      get :search
    end
    resources :reservations, only: %i[create]
  end
  resources :boyfriends, only: %i[show] do
    collection do
      get :ville
    end
  end
  resources :reservations, only: %i[destroy update]
  root to: 'boyfriends#index'
end

app/views/shared/_background.html.erb
<link href="/assets/stylesheets/_index.scss" rel="stylesheet">
<script src="javascript/chennels/balls.js"></script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">LoueMonEx.com</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <%= link_to "Boyfriends' Home", root_path, class: "nav-link" %>
        </li>
    </ul>

    <ul class="navbar-nav mr-auto">
      <%= form_tag search_path, method: :get do %>
        <div class="d-flex">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a boyfriend"
          %>
          <%= submit_tag "Search", class: "btn btn-primary" %>
        </div>
      <% end %>
    </ul>

  <div class="dropdown">
      <% if signed_in? %>

         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= cl_image_tag current_user.avatar if current_user.avatar.attached?%> Hi, <%= current_user.nickname %> <span class="caret"></span></a>

      <% else %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account Info <span class="caret"></span></a>
      <% end %>
     <% if signed_in? %>
        <ul class="dropdown-menu">
          <a href="/boyfriends/new" class="dropdown-item"><i class="fa fa-user-o"></i> Create a boyfriend</a>
          <% link_to "dashboard", reservations_dashboard_path, class: "dropdown-item" %>
          <div class="divider dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </ul>
        <ul class="dropdown-menu">
   </ul>
      <% else %>
        <a href="/users/sign_in" class="dropdown-item"><i class="fa fa-user-o"></i> Log In</a>
        <a href="/users/sign_up" class="dropdown-item"><i class="fa fa-signup-o"></i> Sign Up</a>
      <% end %>
    </ul>
  </div>
</nav>