config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'search', to: "boyfriends#search", as: "search"
  delete 'boyfriends/:id', to: 'boyfriends#destroy', as: 'delete_boyfriend'
  # patch 'boyfriends/:id', to: 'boyfriends#update', as: 'update_boyfriend'

  get 'reservations/dashboard', to: "reservations#dashboard"
  get "confirmation", to:'boyfriends#confirmation', as: 'confirmation'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boyfriends, only: %i[show create new edit update destroy] do
    collection do
      get :search
    end
    resources :reservations, only: %i[create]
  end
  resources :boyfriends, only: %i[show] do
    collection do
      get :ville
    end
  end
  resources :reservations, only: %i[destroy update]
  root to: 'boyfriends#index'
end

app/models/boyfriend.rb
class Boyfriend < ApplicationRecord
  geocoded_by :ville
  after_validation :geocode, if: :will_save_change_to_ville?
  belongs_to :user
  has_many :reservations, dependent: :destroy
  validates :ville, presence: true
  validates :age, presence: true
  validates :description, presence: true
  validates :name, presence: true, uniqueness: true
  has_many_attached :photos
  include PgSearch::Model
    pg_search_scope :search_by_name_and_ville,
      against: [:name, :ville],
      using: {
        tsearch: { prefix: true } # <-- now `superman batm` will return something!
      }
end

app/controllers/boyfriends_controller.rb
class BoyfriendsController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show, :search]

 def index
    @boyfriends = Boyfriend.all

    @markers = @boyfriends.geocoded.map do |boyfriend|
      {
        lat: boyfriend.latitude,
        lng: boyfriend.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { boyfriend: boyfriend })
      }
    end
  end

  def search
    if params[:query].present?
      @boyfriend = Boyfriend.search_by_name_and_ville(params[:query])
      @results = @boyfriend
    else "No boyfriend found"
    end
  end

  def show
    @boyfriend = Boyfriend.find(params[:id])
  end

  def new
    @boyfriend = Boyfriend.new
  end

  def create
    @boyfriend = Boyfriend.new(boyfriend_params)
    # @boyfriend = BoyfriendService.find(params[:service_id])
    # @boyfriend.boyfriend_service = @boyfriend
    @boyfriend.user = current_user
    @boyfriend.save
    redirect_to root_path
  end

  def edit
    @boyfriend = Boyfriend.find(params[:id])
  end

  def update
    @boyfriend = Boyfriend.find(params[:id])
    @boyfriend.update(boyfriend_params)
    @boyfriend.save
    redirect_to root_path
  end

  def destroy
    @boyfriend = Boyfriend.find(params[:id])
    @boyfriend.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to root_path
  end

  private

  def boyfriend_params
    params.require(:boyfriend).permit(:name, :age, :ville, :description, :photos, :price)
  end
end

app/views/boyfriends/_form.html.erb
<%= simple_form_for @boyfriend,
  wrapper: :horizontal_form,
  wrapper_mappings: {
    boolean:       :horizontal_boolean,
    check_boxes:   :horizontal_collection,
    date:          :horizontal_multi_select,
    datetime:      :horizontal_multi_select,
    file:          :horizontal_file,
    radio_buttons: :horizontal_collection,
    range:         :horizontal_range,
    time:          :horizontal_multi_select
  } do |f| %>

  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :age %>
  <%= f.input :ville %>
  <%= f.input :price %>

  <%= f.input :photos, as: :file %>

  <%= f.input :description %>


  <div class="form-group row mb-0">
    <div class="col-sm-9 offset-sm-3">
      <%= f.button :submit, class: "btn-primary" %>
      <% if @boyfriend.persisted? %>
        <button class="btn-outline-secondary" type="submit">
        <%= link_to "Delete",
                      delete_boyfriend_path,
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>
      </button>
      <% end %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    </div>
  </div>

<% end %>

app/views/boyfriends/_info_window.html.erb
<h2><%= boyfriend.name %></h2>
<p><%= boyfriend.ville %></p>
<p><%= boyfriend.price %> € / jour</p>

app/views/boyfriends/confirmation.html.erb
<div class="container">
  <div class="mx-auto" style="width: 200px;">
      <div class="card text-center" style="width: 60rem;">
        <div class="card-body justify-center-content">
          <h5 class="card-title">Thank YOU for your reservation</h5>
          <h6 class="card-subtitle mb-2 text-muted">Happy Boyfriend soon</h6>
          <p class="card-text">Please check your dashboard to see the status of your order!
        We hope to see you again soon</p>
          <a href="/reservations/dashboard" class="btn btn-primary">Your dashboard</a>
          <img class="card-img-top" src="https://www.pngkit.com/png/full/277-2773511_happy-guy-guy-happy.png" alt="Card image cap">
        </div>
      </div>
  </div>
</div>

app/views/boyfriends/dashboard.html.erb
 <!--  id: 9,
  user_id: 78,
  boyfriend_id: 20, récupération du vendeur ici
  start_date: Wed, 10 Mar 2021,
  end_date: Fri, 12 Mar 2021,
  created_at: Wed, 10 Mar 2021 18:35:01 UTC +00:00,
  updated_at: Wed, 10 Mar 2021 18:35:01 UTC +00:00,
  statut: "pending">] -->

app/views/boyfriends/edit.html.erb
<%= render 'form', boyfriend: @boyfriend %>

app/views/boyfriends/index.html.erb
<div id="image-banner">
  <h1 class="image-banner-title">LoueMonEx</h1>
  <h3>Gagnez beacoup d'argent grâce à vos Ex,</h3>
  <h3>c'est possible</h3>
</div>

<div id="map"
      style="width: 100%; height: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

<div class="banner-separator">

</div>

  <div class="container">
    <% @boyfriends.each do |boyfriend| %>

      <div class="card" style="width: 21rem">
        <% if boyfriend.photos.attached? %>
          <%= cl_image_tag boyfriend.photos.first.key, class: "card-img-top", height: 160, width: 80 %>
        <% else %>
          <%= cl_image_tag 'missing_bf', class: "card-img-top", height: 160, width: 80 %>
        <% end %>
        <div class="card-index-body">
          <h5 class="card-index-title"><%= boyfriend.name %></h5>
          <p><%= boyfriend.age%> ans </p>
          <p><%= boyfriend.ville %></p>
          <p><%= boyfriend.price%> € / jour </p>
          <p class="card-index-text"><%= boyfriend.description %></p>
        </div>
        <div class="card-index-footer">
          <%= link_to 'Réserver', boyfriend_path(boyfriend), class: 'btn btn-primary btn-block' %>
        </div>
      </div>

    <% end %>
  </div>

app/views/boyfriends/new.html.erb
<%= render 'form', boyfriend: @boyfriend %>

app/views/boyfriends/search.html.erb
<h1>Search Results</h1>
<div class="container">
  <% @results.each do |boyfriend| %>
    <div class="card" style="width: 18rem;">
      <% if boyfriend.photos.attached? %>
        <%= cl_image_tag boyfriend.photos.first.key, class: "card-img-top", height: 160, width: 80 %>
      <% else %>
        <%= cl_image_tag 'missing_bf', class: "card-img-top", height: 160, width: 80 %>
      <% end %>
      <div class="card-index-body">
        <h5 class="card-index-title"><%= boyfriend.name %></h5>
        <p><%= boyfriend.age%> ans</p>
        <p class="card-index-text"><%= boyfriend.ville %></p>
        <p class="card-index-text"><%= boyfriend.description %></p>
      </div>
      <div class="card-index-footer">
        <%= link_to 'Réserver', boyfriend_path(boyfriend), class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  <% end %>
</div>

app/views/boyfriends/show.html.erb
<div class="container">
  <div class="container">
    <div class="card" style="width: 25rem; margin-top: 16px">
      <% if @boyfriend.photos.attached? %>
        <%= cl_image_tag @boyfriend.photos.first.key, class: "card-img-top", height: 250, width: 150 %>
      <% else %>
        <%= cl_image_tag 'missing_bf', class: "card-img-top", height: 250, width: 150 %>
      <% end %>
      <div class="card-body">
        <div class="card-text">
          <h1><%= @boyfriend.name %></h1>
        <br>
          <h4>Description</h4>
          <p><%= @boyfriend.description %></p>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to 'Back to the menu', root_path, class: 'link-primary' %>
      </div>
      <% if @boyfriend.user == current_user %>
      <div class="card-footer">
          <%= link_to edit_boyfriend_path(@boyfriend) do%>
          update Boyfriend
          <% end %>
      </div>
      <% end %>
    </div>

  </div>
    <div class ="resa">
      <%= simple_form_for [@boyfriend,Reservation.new] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.submit "request reservation", class: "btn btn-primary" %>

      <% end %>
    </div>
</div>