config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'search', to: "boyfriends#search", as: "search"
  delete 'boyfriends/:id', to: 'boyfriends#destroy', as: 'delete_boyfriend'
  # patch 'boyfriends/:id', to: 'boyfriends#update', as: 'update_boyfriend'

  get 'reservations/dashboard', to: "reservations#dashboard"
  get "confirmation", to:'boyfriends#confirmation', as: 'confirmation'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boyfriends, only: %i[show create new edit update destroy] do
    collection do
      get :search
    end
    resources :reservations, only: %i[create]
  end
  resources :boyfriends, only: %i[show] do
    collection do
      get :ville
    end
  end
  resources :reservations, only: %i[destroy update]
  root to: 'boyfriends#index'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :boyfriend

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def new
    # we need @restaurant in our `simple_form_for`
    @boyfriend = Boyfriend.find(params[:boyfriend_id])
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @boyfriend = Boyfriend.find(params[:boyfriend_id])
    @user = current_user
    @reservation.boyfriend = @boyfriend
    @reservation.user = @user
    @reservation.save
    redirect_to confirmation_path
  end


  def dashboard
    # @myreservations : user acheteur
    @myreservations = Reservation.where(user: current_user)
    # @myboyfriendsreservations : user vendeur
    #
    @myboyfriendsreservations = []
    # récupérer les boyfriends du current user
    myboyfriends = Boyfriend.where(user: current_user)
    # itérer sur chaque boyfriend ajouter dans @myboyfriendsreservation les résas du boyfriend
    myboyfriends.each do |boyfriend|
      @myboyfriendsreservations << boyfriend.reservations
    end
    @myboyfriendsreservations.flatten!
  end

  def update
    @reservation = Reservation.find(params[:id])
    if params[:statut] == "confirmed"
      @reservation.statut = "confirmed"
    elsif params[:statut] == "refused"
      @reservation.statut = "refused"
    end
    @reservation.save
    redirect_to reservations_dashboard_path
  end


  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_dashboard_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :statut)
  end
end

app/views/reservations/dashboard.html.erb
<h1>Your Dashboard</h1>
<h2> Vos achats </h2>
  <div class="container">
    <% @myreservations.each do |reservation| %>
      <div class="card" style="width: 18rem; height: 350px">
        <% if reservation.statut == "pending" %>
          <h3> Reservation en attente de confirmation </h3>
        <% elsif reservation.statut == "confirmed" %>
          <h3> Reservation confirmée par le vendeur </h3>
        <% else %>
          <h3> Réservation refusée </h3>
        <% end %>
        <h5><%= reservation.boyfriend.name %></h5>
        <p><%= reservation.boyfriend.age%> ans</p>
        <p><%= reservation.boyfriend.ville %></p>
      <div class="card-index-footer">
        <p> du <%= reservation.start_date %></p>
        <p> au <%= reservation.end_date %></p>
        <p><%= reservation.boyfriend.price %> € / jour</p>
         <%= link_to 'Annuler', reservation_path(reservation), method: :delete, class: 'btn btn-outline-danger btn-block' %>
      </div>
    </div>
    <% end %>
  </div>

<h2> Vos Exs </h2>
  <div class="container">
    <% @myboyfriendsreservations.each do |reservation| %>
      <% if reservation.statut == "pending"%>
       <div class="card" style="width: 18rem; height: 350px">
          <h3> Reservation à confirmer </h3>
          <h5><%= reservation.boyfriend.name %></h5>
          <p><%= reservation.boyfriend.ville %></p>
        </div>
        <div class="card-index-footer">
          <p> du <%= reservation.start_date %></p>
          <p> au <%= reservation.end_date %></p>
          <p> <%= reservation.boyfriend.price %> € / jour</p>
          <%= link_to 'Confirmer', reservation_path(reservation, statut: "confirmed"), method: :patch, class: 'btn btn-primary btn-block' %>
          <%= link_to 'Refuser', reservation_path(reservation, statut: "refused"), method: :patch, class: 'btn btn-warning btn-block' %>
        </div>
      <% elsif reservation.statut == "confirmed"%>
          <div class="card" style="width: 18rem; height: 350px">
            <h3> Reservation confirmée </h3>
            <h5><%= reservation.boyfriend.name %></h5>
            <p><%= reservation.boyfriend.ville %></p>
              <div class="card-index-footer">
                <p> du <%= reservation.start_date %></p>
                <p> au <%= reservation.end_date %></p>
                <p><%= reservation.boyfriend.price %> €/ jour</p>
                <%= link_to 'Refuser', reservation_path(reservation, statut: "refused"), method: :patch, class: 'btn btn-warning btn-block' %>
              </div>
          </div>
      <% else %>
        <div class="card" style="width: 18rem; height: 350px">
          <h3> Reservation annulée </h3>
          <h5><%= reservation.boyfriend.name %></h5>
          <p><%= reservation.boyfriend.ville %></p>
            <div class="card-index-footer">
              <p> du <%= reservation.start_date %></p>
              <p> au <%= reservation.end_date %></p>
              <p><%= reservation.boyfriend.price %> €/ jour</p>
              <%= link_to 'Confirmer', reservation_path(reservation, statut: "confirmed"), method: :patch, class: 'btn btn-primary btn-block' %>
            </div>
        </div>
    <% end %>
      <% end %>
  </div>